# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DiscoverSUTD-2021-microsite
subtitle: Project Page for organising DiscoverSUTD 2021

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/DiscoverSUTD-2021-microsite'

# Author/Organization info to be displayed in the templates
author:
  name: OpenSUTD
  url: https://opensutd.org/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true

- text: Programs
  url: programs/
  internal: true

- text: Contributing
  url: contributing/
  internal: true

- text: Proposal Details
  url: proposal_details/
  internal: true

- text: Lab Sessions
  url: lab_sessions/
  internal: true

- text: For Alumnis
  url: for_alumnis/
  internal: true
  
- text: Site repo
  url: https://github.com/castlemas/DiscoverSUTD-2021-microsite
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: DiscoverSUTD 2021
  description: Master Repository
  url: https://github.com/castlemas/DiscoverSUTD-2021-microsite

# Style Variables
brand_color: "#2cb34a"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
